#!/bin/bash 

WID=35651589

sleep 1

cho "goto Telegram window"
xdotool windowactivate $WID

echo "Start to bombing..."

sleep 2

for j in {1..5000}
do
	echo "Bombing - bomb spent: $j"
	xdotool mousemove 1056 613 click 1 &
	sleep 3

done

echo "Done..!"