#!/bin/bash 

WID=27262980

sleep 2

while :
do 
	echo "goto Telegram window"
	xdotool windowactivate $WID

	echo "Tarik bet"
	xdotool type "/casino_hasil"
	xdotool key Return
	sleep 3

	echo "Pasang bet"
	xdotool type "/casino_UltraLuck_7_5e9"
	xdotool key Return
	sleep 3

	xdotool windowactivate $WID
	echo "Feedx Special Animal"
	xdotool type "/feedx"
	xdotool key Return
	sleep 3

	echo "Ambil hasil & Feed animal"
	xdotool type "/ambilHasil"
	xdotool key Return
	sleep 3

	xdotool type "/feed"
	xdotool key Return
	sleep 3


	xdotool windowactivate $WID
	echo "Ambil panen - Lahan pribadi"
	xdotool type "/ambilPanen"
	xdotool key Return
	sleep 3

	echo "Tanam kacang tanah - Lahan pribadi"
	xdotool type "/tanam_Peanut_403"
	xdotool key Return
	sleep 3

	echo "Siram - Lahan pribadi"
	xdotool type "/siram"
	xdotool key Return
	sleep 3

	xdotool type "/aktifkan_sekarang"
	xdotool key Return
	sleep 3


	echo "Waiting..!"
	echo "  "
	sleep 101

done 
