#!/bin/bash 

WID=25165829

echo "Nernak"

sleep 2

for i in {1..1000}
do
	xdotool windowactivate $WID

	echo "Run - $i"

	echo "Ambil Ternak"
	xdotool type "/ambilHewan"
	xdotool key Return
	sleep 2.5

	echo "Beri Makan"
	xdotool type "/add_BayiBabi_130"
	xdotool key Return
	sleep 2.5

	echo " "
done

echo "Done..!"