#!/bin/bash 

WID=25165829

sleep 2

xdotool windowactivate $WID

for i in {1..500}
do 
	echo "Round - $i"
	xdotool windowactivate $WID
	
	echo "Ambil panen"
	xdotool type "/harvestnow"
	xdotool key Return
	sleep 3

	echo "Tanam Nanas Keramat"
	xdotool type "/tanam_Peanut_1966"
	xdotool key Return
	sleep 3

	echo " "

done 