#!/bin/bash 

WID=23068677

sleep 2

while :
do 
	echo "goto Telegram window"
	xdotool windowactivate $WID

	echo "Tarik bet"
	xdotool type "/casino_hasil"
	xdotool key Return
	sleep 3

	echo "Pasang bet"
	xdotool type "/casino_UltraLuck_16_5e9"
	xdotool key Return
	sleep 3

	xdotool type "/aktifkan_sekarang"
	xdotool key Return
	sleep 3

	echo "Waiting..!"
	echo "  "
	sleep 55

done 
