#!/bin/bash 

WID=37748741

sleep 1

cho "goto Telegram window"
xdotool windowactivate $WID

for i in {1..555}
do 
	echo "Panen - $i"
	xdotool windowactivate $WID
	xdotool type "/pfs_AreaClassE_panensekarang"
	xdotool key Return
	sleep 2.5

	xdotool windowactivate $WID
	xdotool type "/pfs_AreaClassD_panensekarang"
	xdotool key Return
	sleep 2.5

	xdotool windowactivate $WID
	xdotool type "/pfs_AreaClassC_panensekarang"
	xdotool key Return
	sleep 2.5
	
done 
