#!/bin/bash 

WID=39845893

sleep 1

cho "goto Telegram window"
xdotool windowactivate $WID

echo "Moa..."

sleep 2

for j in {6998..7038}
do
	echo "Bidding 18${j} 1q"
	for i in {1..2}
	do
		xdotool type "/lelangGroup_18${j}_1e15"
		xdotool key Return
		sleep 2
	done
done

echo "Done..!"